In [1]:
import numpy as np

In [2]:
a=np.random.random((2,2))

In [3]:
print(a)

[[0.83368465 0.745074  ]
 [0.34532316 0.59175711]]


In [4]:
print(np.arange(0,20,5))

[ 0  5 10 15]


In [5]:
print(np.linspace(1,10,10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
a=np.random.random((3,4))

In [7]:
print(a)

[[0.58248288 0.28733817 0.64403927 0.81929765]
 [0.64794302 0.41271813 0.05087733 0.80455015]
 [0.27210048 0.47389562 0.52052741 0.31166689]]


In [8]:
b=a.reshape(3,2,2)

In [9]:
print(b)

[[[0.58248288 0.28733817]
  [0.64403927 0.81929765]]

 [[0.64794302 0.41271813]
  [0.05087733 0.80455015]]

 [[0.27210048 0.47389562]
  [0.52052741 0.31166689]]]


In [10]:
print(b.reshape(1,1,12))

[[[0.58248288 0.28733817 0.64403927 0.81929765 0.64794302 0.41271813
   0.05087733 0.80455015 0.27210048 0.47389562 0.52052741 0.31166689]]]


In [11]:
#slicing array
print(a[:2,::3])

[[0.58248288 0.81929765]
 [0.64794302 0.80455015]]


In [12]:
temp = a[[0, 1, 2], [3, 2, 1]] 

In [13]:
print(temp)

[0.81929765 0.05087733 0.47389562]


In [14]:
print(a)

[[0.58248288 0.28733817 0.64403927 0.81929765]
 [0.64794302 0.41271813 0.05087733 0.80455015]
 [0.27210048 0.47389562 0.52052741 0.31166689]]


In [15]:
print(a.T)

[[0.58248288 0.64794302 0.27210048]
 [0.28733817 0.41271813 0.47389562]
 [0.64403927 0.05087733 0.52052741]
 [0.81929765 0.80455015 0.31166689]]


In [16]:
print(a.max())

0.8192976469682651


In [17]:
print(a.max(axis=1))

[0.81929765 0.80455015 0.52052741]


In [18]:
print(a.max(axis=0))

[0.64794302 0.47389562 0.64403927 0.81929765]


In [19]:
print(a)

[[0.58248288 0.28733817 0.64403927 0.81929765]
 [0.64794302 0.41271813 0.05087733 0.80455015]
 [0.27210048 0.47389562 0.52052741 0.31166689]]


In [20]:
print(a.sum())

5.827437006740975


In [21]:
print(a.cumsum(axis=1))

[[0.58248288 0.86982105 1.51386033 2.33315797]
 [0.64794302 1.06066115 1.11153849 1.91608864]
 [0.27210048 0.7459961  1.2665235  1.57819039]]


In [22]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,4],[3,2]])
print(a+b)

[[3 6]
 [6 6]]


In [23]:
print(a*b)

[[2 8]
 [9 8]]


In [24]:
print(a.dot(b))

[[ 8  8]
 [18 20]]


In [25]:
a = np.array([0, np.pi/2, np.pi])

In [26]:
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [27]:
import pandas as pd

In [28]:
S=pd.Series()
print(S)
new=np.array([1,2,3,'data','blue'])
S=pd.Series(new)
print(S)

Series([], dtype: float64)
0       1
1       2
2       3
3    data
4    blue
dtype: object


C:\Users\22anj\AppData\Local\Temp\ipykernel_7076\2274024371.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  S=pd.Series()


In [29]:
New={'X':[2,4,6,8,10],'Y':[4,8,10,12,15]}
df=pd.DataFrame(New)
print(df)

    X   Y
0   2   4
1   4   8
2   6  10
3   8  12
4  10  15


In [31]:
from sklearn import datasets